"""HID mouse button bit masks."""

LEFT = LEFT_BUTTON = 0x01
RIGHT = RIGHT_BUTTON = 0x02
MIDDLE = MIDDLE_BUTTON = 0x04
SIDE = SIDE_BUTTON = 0x08
EXTRA = EXTRA_BUTTON = 0x10
FORWARD = FORWARD_BUTTON = 0x20
BACK = BACK_BUTTON = 0x40
TASK = TASK_BUTTON = 0x80
